# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171022_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='packages_installs',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
