# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import downloadapp.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('display', models.ImageField(max_length=200, storage=downloadapp.storage.saveSmartFileDisp(), upload_to='uploads/display/<django.db.models.fields.CharField>')),
                ('isPublished', models.BooleanField(default=False)),
                ('catagory', models.CharField(choices=[('GAM', 'Games'), ('APP', 'Apps'), ('DEV', 'Devloper tools'), ('MED', 'Media')], default='APP', max_length=3)),
                ('software', models.FileField(storage=downloadapp.storage.saveSmartFileSoft(), upload_to='uploads/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
