# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='isPublished',
        ),
        migrations.AddField(
            model_name='package',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='stage',
            field=models.NullBooleanField(default=None),
        ),
    ]
