# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import downloadapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='display',
            field=models.ImageField(max_length=200, storage=downloadapp.storage.saveSmartFileDisp(), upload_to=models.CharField(max_length=200)),
        ),
    ]
