# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0002_auto_20171210_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='stage',
            field=models.CharField(choices=[('LOK', 'Certification'), ('LIV', 'Live!')], default='LOK', max_length=3),
        ),
    ]
