# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import downloadapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0002_auto_20170902_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='software',
            field=models.FileField(storage=downloadapp.storage.saveSmartFileSoft(), upload_to=models.CharField(max_length=200)),
        ),
    ]
