# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0003_auto_20180113_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='owner',
        ),
    ]
