# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import downloadapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0004_auto_20170902_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shot',
            field=models.ImageField(default=None, max_length=200, storage=downloadapp.storage.saveSmartFileShot(), upload_to=''),
            preserve_default=False,
        ),
    ]
