# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadapp', '0005_package_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='installs',
            field=models.IntegerField(default=0),
        ),
    ]
